name: machine-learning
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - conda-forge::ipykernel
  - conda-forge::debugpy
  - pip
  - pip:
    - opencv-contrib-python
    - jupyterlab
    - xeus-python
    - opencv-python
    - pillow
    - ultralytics
    - ipywidgets
    - deepface
    - scenedetect

